"""initial_schema

Revision ID: 1de770da007e
Revises: 
Create Date: 2026-05-30 16:36:06.549128

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1de770da007e'
down_revision = None
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_class_name')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=72), nullable=False),
    sa.Column('role', sa.Enum('admin', 'teacher', 'student', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('sections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('class_id', 'name', name='uq_section_class_name')
    )
    op.create_index(op.f('ix_sections_class_id'), 'sections', ['class_id'], unique=False)
    op.create_table('streaks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('longest_streak', sa.Integer(), nullable=False),
    sa.Column('last_session_date', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id')
    )
    op.create_table('student_skill_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('avg_accuracy_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('avg_fluency_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('avg_pronunciation_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('avg_overall_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('total_sessions_completed', sa.Integer(), nullable=False),
    sa.Column('total_lessons_completed', sa.Integer(), nullable=False),
    sa.Column('strength_tags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('weakness_tags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id')
    )
    op.create_table('lessons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('language', sa.Enum('english', 'tamil', name='language'), nullable=False),
    sa.Column('pdf_storage_key', sa.String(length=1024), nullable=False),
    sa.Column('pdf_extracted_text', sa.Text(), nullable=True),
    sa.Column('pdf_extraction_status', sa.Enum('pending', 'success', 'failed', name='pdfextractionstatus'), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pdf_storage_key')
    )
    op.create_index(op.f('ix_lessons_section_id'), 'lessons', ['section_id'], unique=False)
    op.create_table('student_section_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('assigned_by', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('unassigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_section_assignments_section_id'), 'student_section_assignments', ['section_id'], unique=False)
    op.create_index(op.f('ix_student_section_assignments_student_id'), 'student_section_assignments', ['student_id'], unique=False)
    op.create_index('uq_student_active_section', 'student_section_assignments', ['student_id'], unique=True, postgresql_where='is_active = true')
    op.create_table('teacher_section_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('assigned_by', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('unassigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teacher_section_assignments_section_id'), 'teacher_section_assignments', ['section_id'], unique=False)
    op.create_index(op.f('ix_teacher_section_assignments_teacher_id'), 'teacher_section_assignments', ['teacher_id'], unique=False)
    op.create_index('uq_teacher_section_active', 'teacher_section_assignments', ['teacher_id', 'section_id'], unique=True, postgresql_where='is_active = true')
    op.create_table('weekly_leaderboard',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('week_end', sa.Date(), nullable=False),
    sa.Column('sessions_completed', sa.SmallInteger(), nullable=False),
    sa.Column('avg_overall_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('avg_accuracy_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('avg_fluency_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('composite_score', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('rank', sa.SmallInteger(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('section_id', 'student_id', 'week_start', name='uq_leaderboard_entry')
    )
    op.create_index(op.f('ix_weekly_leaderboard_section_id'), 'weekly_leaderboard', ['section_id'], unique=False)
    op.create_index(op.f('ix_weekly_leaderboard_student_id'), 'weekly_leaderboard', ['student_id'], unique=False)
    op.create_table('reading_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('lesson_id', sa.UUID(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('in_progress', 'completed', 'abandoned', name='sessionstatus'), nullable=False),
    sa.Column('language', sa.String(length=20), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('assessment_status', sa.Enum('pending', 'processing', 'completed', 'failed', name='assessmentstatus'), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('retry_count', sa.SmallInteger(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reading_sessions_lesson_id'), 'reading_sessions', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_reading_sessions_student_id'), 'reading_sessions', ['student_id'], unique=False)
    op.create_table('assessment_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('accuracy_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('fluency_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('pronunciation_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('overall_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('words_per_minute', sa.SmallInteger(), nullable=False),
    sa.Column('pause_count', sa.SmallInteger(), nullable=False),
    sa.Column('filler_word_count', sa.SmallInteger(), nullable=False),
    sa.Column('mispronounced_words', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('pronunciation_issues', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('grammatical_mistakes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('strength_tags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('weakness_tags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('assessed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['reading_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_results_session_id'), 'assessment_results', ['session_id'], unique=True)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assessment_results_session_id'), table_name='assessment_results')
    op.drop_table('assessment_results')
    op.drop_index(op.f('ix_reading_sessions_student_id'), table_name='reading_sessions')
    op.drop_index(op.f('ix_reading_sessions_lesson_id'), table_name='reading_sessions')
    op.drop_table('reading_sessions')
    op.drop_index(op.f('ix_weekly_leaderboard_student_id'), table_name='weekly_leaderboard')
    op.drop_index(op.f('ix_weekly_leaderboard_section_id'), table_name='weekly_leaderboard')
    op.drop_table('weekly_leaderboard')
    op.drop_index('uq_teacher_section_active', table_name='teacher_section_assignments', postgresql_where='is_active = true')
    op.drop_index(op.f('ix_teacher_section_assignments_teacher_id'), table_name='teacher_section_assignments')
    op.drop_index(op.f('ix_teacher_section_assignments_section_id'), table_name='teacher_section_assignments')
    op.drop_table('teacher_section_assignments')
    op.drop_index('uq_student_active_section', table_name='student_section_assignments', postgresql_where='is_active = true')
    op.drop_index(op.f('ix_student_section_assignments_student_id'), table_name='student_section_assignments')
    op.drop_index(op.f('ix_student_section_assignments_section_id'), table_name='student_section_assignments')
    op.drop_table('student_section_assignments')
    op.drop_index(op.f('ix_lessons_section_id'), table_name='lessons')
    op.drop_table('lessons')
    op.drop_table('student_skill_profiles')
    op.drop_table('streaks')
    op.drop_index(op.f('ix_sections_class_id'), table_name='sections')
    op.drop_table('sections')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('classes')
    # ### end Alembic commands ###
